apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-web-service
  name: node-web-service
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-web-service
status:
  loadBalancer: {}
